server:
  port: 8084
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz94kwe2ue127wj29bo.mysql.rds.aliyuncs.com:3306/ebook_test
    username: root
    password: Root2019
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    port: 6379
logging:
  config: classpath:log4j2.xml
ebook:
  retry: 5
